//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class Cihazlar : XPObject
    {
        string fCihazAdi;
        public string CihazAdi
        {
            get { return fCihazAdi; }
            set { SetPropertyValue<string>(nameof(CihazAdi), ref fCihazAdi, value); }
        }
        string fCihazId;
        public string CihazId
        {
            get { return fCihazId; }
            set { SetPropertyValue<string>(nameof(CihazId), ref fCihazId, value); }
        }
        string fModeli;
        public string Modeli
        {
            get { return fModeli; }
            set { SetPropertyValue<string>(nameof(Modeli), ref fModeli, value); }
        }
        string fOkuyucuSayisi;
        public string OkuyucuSayisi
        {
            get { return fOkuyucuSayisi; }
            set { SetPropertyValue<string>(nameof(OkuyucuSayisi), ref fOkuyucuSayisi, value); }
        }
        [Association(@"KapilarReferencesCihazlar"), Aggregated]
        public XPCollection<Kapilar> Kapilars { get { return GetCollection<Kapilar>(nameof(Kapilars)); } }
    }

}
