//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class GirisCikislar : XPObject
    {
        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue<DateTime>(nameof(Tarih), ref fTarih, value); }
        }
        Kapilar fKapi;
        public Kapilar Kapi
        {
            get { return fKapi; }
            set { SetPropertyValue<Kapilar>(nameof(Kapi), ref fKapi, value); }
        }
        decimal fTutar;
        public decimal Tutar
        {
            get { return fTutar; }
            set { SetPropertyValue<decimal>(nameof(Tutar), ref fTutar, value); }
        }
        KartGrubu fKartGrubu;
        public KartGrubu KartGrubu
        {
            get { return fKartGrubu; }
            set { SetPropertyValue<KartGrubu>(nameof(KartGrubu), ref fKartGrubu, value); }
        }
        KartBilgileri fKartBilgileri;
        [Association(@"GirisCikislarReferencesKartBilgileri")]
        public KartBilgileri KartBilgileri
        {
            get { return fKartBilgileri; }
            set { SetPropertyValue<KartBilgileri>(nameof(KartBilgileri), ref fKartBilgileri, value); }
        }
        bool fiade;
        public bool iade
        {
            get { return fiade; }
            set { SetPropertyValue<bool>(nameof(iade), ref fiade, value); }
        }
    }

}
