//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class indirimler : XPObject
    {
        DateTime fTarihinden;
        public DateTime Tarihinden
        {
            get { return fTarihinden; }
            set { SetPropertyValue<DateTime>(nameof(Tarihinden), ref fTarihinden, value); }
        }
        DateTime fTarihine;
        public DateTime Tarihine
        {
            get { return fTarihine; }
            set { SetPropertyValue<DateTime>(nameof(Tarihine), ref fTarihine, value); }
        }
        int findirimOrani;
        public int indirimOrani
        {
            get { return findirimOrani; }
            set { SetPropertyValue<int>(nameof(indirimOrani), ref findirimOrani, value); }
        }
        decimal findirimTutari;
        public decimal indirimTutari
        {
            get { return findirimTutari; }
            set { SetPropertyValue<decimal>(nameof(indirimTutari), ref findirimTutari, value); }
        }
        KartGrubu fKartGrubu;
        public KartGrubu KartGrubu
        {
            get { return fKartGrubu; }
            set { SetPropertyValue<KartGrubu>(nameof(KartGrubu), ref fKartGrubu, value); }
        }
        string fAciklama;
        public string Aciklama
        {
            get { return fAciklama; }
            set { SetPropertyValue<string>(nameof(Aciklama), ref fAciklama, value); }
        }
    }

}
