//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class Kapilar : XPObject
    {
        string fAdi;
        public string Adi
        {
            get { return fAdi; }
            set { SetPropertyValue<string>(nameof(Adi), ref fAdi, value); }
        }
        Cihazlar fCihaz;
        [Association(@"KapilarReferencesCihazlar")]
        public Cihazlar Cihaz
        {
            get { return fCihaz; }
            set { SetPropertyValue<Cihazlar>(nameof(Cihaz), ref fCihaz, value); }
        }
    }

}
