//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class KartOdeme : XPObject
    {
        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue<DateTime>(nameof(Tarih), ref fTarih, value); }
        }
        decimal fYatanTutar;
        public decimal YatanTutar
        {
            get { return fYatanTutar; }
            set { SetPropertyValue<decimal>(nameof(YatanTutar), ref fYatanTutar, value); }
        }
        bool fiade;
        public bool iade
        {
            get { return fiade; }
            set { SetPropertyValue<bool>(nameof(iade), ref fiade, value); }
        }
        KartBilgileri fKartBilgisi;
        [Association(@"KartOdemeReferencesKartBilgileri")]
        public KartBilgileri KartBilgisi
        {
            get { return fKartBilgisi; }
            set { SetPropertyValue<KartBilgileri>(nameof(KartBilgisi), ref fKartBilgisi, value); }
        }
        bool fKrediKarti;
        public bool KrediKarti
        {
            get { return fKrediKarti; }
            set { SetPropertyValue<bool>(nameof(KrediKarti), ref fKrediKarti, value); }
        }
    }

}
