//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class KartBilgileri : XPObject
    {
        string fKartNo;
        public string KartNo
        {
            get { return fKartNo; }
            set { SetPropertyValue<string>(nameof(KartNo), ref fKartNo, value); }
        }
        string fAdiSoyadi;
        public string AdiSoyadi
        {
            get { return fAdiSoyadi; }
            set { SetPropertyValue<string>(nameof(AdiSoyadi), ref fAdiSoyadi, value); }
        }
        string fTelefonu;
        public string Telefonu
        {
            get { return fTelefonu; }
            set { SetPropertyValue<string>(nameof(Telefonu), ref fTelefonu, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        decimal fKartBakiye;
        public decimal KartBakiye
        {
            get { return fKartBakiye; }
            set { SetPropertyValue<decimal>(nameof(KartBakiye), ref fKartBakiye, value); }
        }
        KartGrubu fKartGrubu;
        public KartGrubu KartGrubu
        {
            get { return fKartGrubu; }
            set { SetPropertyValue<KartGrubu>(nameof(KartGrubu), ref fKartGrubu, value); }
        }
        bool fSinirsizGecis;
        public bool SinirsizGecis
        {
            get { return fSinirsizGecis; }
            set { SetPropertyValue<bool>(nameof(SinirsizGecis), ref fSinirsizGecis, value); }
        }
        indirimler findirimli;
        public indirimler indirimli
        {
            get { return findirimli; }
            set { SetPropertyValue<indirimler>(nameof(indirimli), ref findirimli, value); }
        }
        string fKartID;
        public string KartID
        {
            get { return fKartID; }
            set { SetPropertyValue<string>(nameof(KartID), ref fKartID, value); }
        }
        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue<DateTime>(nameof(Tarih), ref fTarih, value); }
        }
        [Association(@"KartOdemeReferencesKartBilgileri"), Aggregated]
        public XPCollection<KartOdeme> KartOdemes { get { return GetCollection<KartOdeme>(nameof(KartOdemes)); } }
        [Association(@"GirisCikislarReferencesKartBilgileri"), Aggregated]
        public XPCollection<GirisCikislar> GirisCikislars { get { return GetCollection<GirisCikislar>(nameof(GirisCikislars)); } }
        [Association(@"SatilanUrunlerReferencesKartBilgileri"), Aggregated]
        public XPCollection<SatilanUrunler> SatilanUrunlers { get { return GetCollection<SatilanUrunler>(nameof(SatilanUrunlers)); } }
    }

}
