//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class Kasa : XPObject
    {
        decimal fNakit;
        public decimal Nakit
        {
            get { return fNakit; }
            set { SetPropertyValue<decimal>(nameof(Nakit), ref fNakit, value); }
        }
        decimal fKrediKarti;
        public decimal KrediKarti
        {
            get { return fKrediKarti; }
            set { SetPropertyValue<decimal>(nameof(KrediKarti), ref fKrediKarti, value); }
        }
        decimal fToplam;
        public decimal Toplam
        {
            get { return fToplam; }
            set { SetPropertyValue<decimal>(nameof(Toplam), ref fToplam, value); }
        }
        string fKasaAdi;
        public string KasaAdi
        {
            get { return fKasaAdi; }
            set { SetPropertyValue<string>(nameof(KasaAdi), ref fKasaAdi, value); }
        }
        [Association(@"KasaDetayReferencesKasa"), Aggregated]
        public XPCollection<KasaDetay> KasaDetays { get { return GetCollection<KasaDetay>(nameof(KasaDetays)); } }
    }

}
