//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.BaseImpl.PermissionPolicy;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class KasaDetay : XPObject
    {
        PermissionPolicyUser fGiseci;
        public PermissionPolicyUser Giseci
        {
            get { return fGiseci; }
            set { SetPropertyValue<PermissionPolicyUser>(nameof(Giseci), ref fGiseci, value); }
        }
        DateTime fTarih;
        public DateTime Tarih
        {
            get { return fTarih; }
            set { SetPropertyValue<DateTime>(nameof(Tarih), ref fTarih, value); }
        }
        decimal fNakitToplam;
        public decimal NakitToplam
        {
            get { return fNakitToplam; }
            set { SetPropertyValue<decimal>(nameof(NakitToplam), ref fNakitToplam, value); }
        }
        decimal fKrediKartiToplam;
        public decimal KrediKartiToplam
        {
            get { return fKrediKartiToplam; }
            set { SetPropertyValue<decimal>(nameof(KrediKartiToplam), ref fKrediKartiToplam, value); }
        }
        decimal fToplamKazanc;
        public decimal ToplamKazanc
        {
            get { return fToplamKazanc; }
            set { SetPropertyValue<decimal>(nameof(ToplamKazanc), ref fToplamKazanc, value); }
        }
        Kasa fKasa;
        [Association(@"KasaDetayReferencesKasa")]
        public Kasa Kasa
        {
            get { return fKasa; }
            set { SetPropertyValue<Kasa>(nameof(Kasa), ref fKasa, value); }
        }
        decimal fTeslimAlinanTutar;
        public decimal TeslimAlinanTutar
        {
            get { return fTeslimAlinanTutar; }
            set { SetPropertyValue<decimal>(nameof(TeslimAlinanTutar), ref fTeslimAlinanTutar, value); }
        }
        decimal fEksikTutar;
        public decimal EksikTutar
        {
            get { return fEksikTutar; }
            set { SetPropertyValue<decimal>(nameof(EksikTutar), ref fEksikTutar, value); }
        }
        string fEksikAciklama;
        [Size(SizeAttribute.Unlimited)]
        public string EksikAciklama
        {
            get { return fEksikAciklama; }
            set { SetPropertyValue<string>(nameof(EksikAciklama), ref fEksikAciklama, value); }
        }
        PermissionPolicyUser fTeslimAlan;
        public PermissionPolicyUser TeslimAlan
        {
            get { return fTeslimAlan; }
            set { SetPropertyValue<PermissionPolicyUser>(nameof(TeslimAlan), ref fTeslimAlan, value); }
        }
        bool fTeslimAlindi;
        public bool TeslimAlindi
        {
            get { return fTeslimAlindi; }
            set { SetPropertyValue<bool>(nameof(TeslimAlindi), ref fTeslimAlindi, value); }
        }
    }

}
