//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace YildizOtomasyon.Module.BusinessObjects.YildizOtomasyonDB
{

    public partial class Urunler : XPObject
    {
        string fBarkodu;
        public string Barkodu
        {
            get { return fBarkodu; }
            set { SetPropertyValue<string>(nameof(Barkodu), ref fBarkodu, value); }
        }
        string fUrunAdi;
        public string UrunAdi
        {
            get { return fUrunAdi; }
            set { SetPropertyValue<string>(nameof(UrunAdi), ref fUrunAdi, value); }
        }
        UrunKategori fKategori;
        public UrunKategori Kategori
        {
            get { return fKategori; }
            set { SetPropertyValue<UrunKategori>(nameof(Kategori), ref fKategori, value); }
        }
        decimal fFiyat;
        public decimal Fiyat
        {
            get { return fFiyat; }
            set { SetPropertyValue<decimal>(nameof(Fiyat), ref fFiyat, value); }
        }
    }

}
